In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
print (a)

[1 2 3 4 5]


In [5]:
import time
a= np.random.rand(1000000)
b= np.random.rand(1000000)

tic= time.time()
c= np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic))+"ms")
c=0
tic= time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("for loop:" + str(1000*(toc-tic))+"ms")

250078.9603046791
Vectorized version:1.0104179382324219ms
250078.9603046821
for loop:602.9980182647705ms


In [6]:
A = np.array([[56,0,4.4,68],
             [1.2,104,52,8],
             [1.8,135,99,0.9]])
print (A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [10]:
cal= A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [11]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [14]:
print(cal.reshape(4,1))

[[ 59. ]
 [239. ]
 [155.4]
 [ 76.9]]


In [15]:
a = np.random.randn(5)
print(a)

[ 0.84569561  0.18280778 -1.01151366  0.80118392 -0.01096127]


In [16]:
print(a.shape)

(5,)


In [17]:
print(a.T)

[ 0.84569561  0.18280778 -1.01151366  0.80118392 -0.01096127]


In [18]:
print(np.dot(a,a.T))

2.41379546651736


In [19]:
a= np.random.randn(5,1)
print(a)

[[ 1.3175352 ]
 [ 1.43993421]
 [-0.24267463]
 [ 0.24435554]
 [-2.78144413]]


In [20]:
print(a.T)

[[ 1.3175352   1.43993421 -0.24267463  0.24435554 -2.78144413]]


In [21]:
print(np.dot(a,a.T))

[[ 1.73589902  1.89716401 -0.31973236  0.32194702 -3.66465056]
 [ 1.89716401  2.07341053 -0.3494355   0.3518559  -4.00509655]
 [-0.31973236 -0.3494355   0.05889097 -0.05929889  0.67498592]
 [ 0.32194702  0.3518559  -0.05929889  0.05970963 -0.67966127]
 [-3.66465056 -4.00509655  0.67498592 -0.67966127  7.73643143]]


In [3]:
import numpy as np
import tensorflow as tf

In [3]:
!pip --version

pip 19.1.1 from C:\ProgramData\Anaconda3\lib\site-packages\pip (python 3.7)



In [10]:
import tensorflow.compat.v1 as tf

In [11]:
tf.__version__

'2.4.0'

In [12]:
w = tf.Variable(0,dtype=tf.float32)
cost = tf.add(tf.add(w**2,tf.multiply(-10,w)),25)
trian = tf.train.GradientDescentOptimizer(0.01).minimize(cost)
#train = tf.optimizers.SGD(0.01).minimize(cost)

init = tf.global_variables_initializer()
session = tf.Session()
session.run(init)
print(session.run(w))

RuntimeError: `loss` passed to Optimizer.compute_gradients should be a function when eager execution is enabled.

In [2]:
import numpy as np
x = np.random.randn(4, 3, 3, 2)

In [12]:
a = np.ones((4, 3, 2))
a

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [9]:
npad = ((0, 0), (2, 2), (3, 3))

In [13]:
b = np.pad(a, pad_width=npad, mode='constant', constant_values=(0,9))

print(b.shape)

(4, 7, 8)


In [14]:
b

array([[[0., 0., 0., 0., 0., 9., 9., 9.],
        [0., 0., 0., 0., 0., 9., 9., 9.],
        [0., 0., 0., 1., 1., 9., 9., 9.],
        [0., 0., 0., 1., 1., 9., 9., 9.],
        [0., 0., 0., 1., 1., 9., 9., 9.],
        [0., 0., 0., 9., 9., 9., 9., 9.],
        [0., 0., 0., 9., 9., 9., 9., 9.]],

       [[0., 0., 0., 0., 0., 9., 9., 9.],
        [0., 0., 0., 0., 0., 9., 9., 9.],
        [0., 0., 0., 1., 1., 9., 9., 9.],
        [0., 0., 0., 1., 1., 9., 9., 9.],
        [0., 0., 0., 1., 1., 9., 9., 9.],
        [0., 0., 0., 9., 9., 9., 9., 9.],
        [0., 0., 0., 9., 9., 9., 9., 9.]],

       [[0., 0., 0., 0., 0., 9., 9., 9.],
        [0., 0., 0., 0., 0., 9., 9., 9.],
        [0., 0., 0., 1., 1., 9., 9., 9.],
        [0., 0., 0., 1., 1., 9., 9., 9.],
        [0., 0., 0., 1., 1., 9., 9., 9.],
        [0., 0., 0., 9., 9., 9., 9., 9.],
        [0., 0., 0., 9., 9., 9., 9., 9.]],

       [[0., 0., 0., 0., 0., 9., 9., 9.],
        [0., 0., 0., 0., 0., 9., 9., 9.],
        [0., 0., 0., 1., 1.,